# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
pool:
  vmImage: 'vs2017-win2016'
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
stages:
- stage: PluginInstall
  displayName: installation
  jobs:
    - job: InstallPlugin
      displayName: Install Plugin
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          npm config set @sap:registry "https://npm.sap.com"
          npm install
        displayName: 'npm install'
      - script: |
          npm install --save-dev eslint
        displayName: 'Install eslint'
      - script: |
          npm install karma --save-dev
        displayName: 'Install Karma'
      - script: |
          npm install karma-cli
        displayName: 'Install karma-Cli'
      - script: |
          npm i -g rimraf
        displayName: 'Install rimraf'
      - script: |
          npm install -g grunt-nwabap-ui5uploader
        displayName: Install grunt ui5 uploader
      - script: |
          npm run lint
        displayName: 'Run eslint'
      - script: |
          npm run karma-ci
        displayName: 'Run unit test and opa test'
      - script: |
          npm install --global @ui5/cli
        displayName: 'UI5-cli'
      - script: |
          ui5 build -a --clean-dest
        displayName: 'Build Application'
      - script: |
          npm install -g grunt-cli
        displayName: Install grunt cli Globally
      - script: |
          npm install grunt --save-dev
        displayName: Install grunt locally
      - script: |
          npm install grunt-nwabap-ui5uploader --save-dev
        displayName: Install grunt ui5uploader locally
      - script: |
          grunt --username="DEV_ECQ2" --password="Welcome1" --server="http://in-blr-1709:8000" --request="S48K901584" --pkg="ZAZUREDEVOPS"
        displayName: 'Deploy process'
